// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lk3skLK6c8YcIpkZDGeAFDIN5pJDIw4',
    appId: '1:664819621240:web:e91d63ada45bea1ad87c8d',
    messagingSenderId: '664819621240',
    projectId: 'projectone-bc198',
    authDomain: 'projectone-bc198.firebaseapp.com',
    storageBucket: 'projectone-bc198.appspot.com',
    measurementId: 'G-KRQLMKCF2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmkTsWBBBrOg1nOA03oFgtwOIzlM8yxFs',
    appId: '1:664819621240:android:02eb9f16029a4de5d87c8d',
    messagingSenderId: '664819621240',
    projectId: 'projectone-bc198',
    storageBucket: 'projectone-bc198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TvQQw49mtBNU4j-Kj3OmiAq2sTBiAxY',
    appId: '1:664819621240:ios:2d503ea53ffbbc1bd87c8d',
    messagingSenderId: '664819621240',
    projectId: 'projectone-bc198',
    storageBucket: 'projectone-bc198.appspot.com',
    iosClientId:
        '664819621240-a8sgveue3dtrjs4ouphm8drkudcbdeos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_TvQQw49mtBNU4j-Kj3OmiAq2sTBiAxY',
    appId: '1:664819621240:ios:2d503ea53ffbbc1bd87c8d',
    messagingSenderId: '664819621240',
    projectId: 'projectone-bc198',
    storageBucket: 'projectone-bc198.appspot.com',
    iosClientId:
        '664819621240-a8sgveue3dtrjs4ouphm8drkudcbdeos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
